### PR TITLE
magnitude_to_decibel support for float16+float64

### PR DESCRIPTION
**Pull request by jamesmishra**
The function kapre.backend.magnitude_to_decibel with the default
arguments throws a TensorFlow type error if `x` is not `float32`.

We can fix this by casting `amin` to `x`'s dtype.

Previously, the Keras layer `kapre.time_frequency.MagnitudeToDecibel`
avoided these errors by casting arguments to `float32`, but this
change also fixes the layer if initialized as
`MagnitudeToDecibel(dtype=tf.float64)` or
`MagnitudeToDecibel(dtype=tf.float16)`

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Thanks! I'm merging it to `kapre-0.3.5` branch which will be released in a couple of weeks. Hope that's fine with you.

**Comment by keunwoochoi** [comment]
Oh and.. would it be possible for you to add a unit test, one that with different dtypes?

**Comment by jamesmishra** [comment]
Oh, thank you! I use Kapre all the time.

I just added an additional `@pytest.mark.parameterize` decorator for `dtype` on `test_magnitude_to_decibel`.  There is slightly more floating point error for the `float16` test, but it looks like it works.

**Comment by keunwoochoi** [comment]
Looks great, merging now. Thanks again for your contribution :)

**Pull request merged**
