### PR TITLE
used tensorflow intead of keras

### PR DESCRIPTION
**Pull request by kongkip**

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Hi, thanks for the PR! I’m at a conference and will review it during or after this weekend.

**Comment by keunwoochoi** [comment]
Hey, I reviewed. I think tests folder and dependencies on `setup.py` should be added too. Thanks for the work though! If you can update it more completely that would be great. If you're busy, I'll try to do it by myself.

**Comment by kongkip** [comment]
hi, nice. Will try to make changes

**Comment by XReyRobert** [comment]
Hello @kongkip please check my comments and attachments in #58. I ran into issues trying to compute Melspectrograms with your PR.

**Comment by keunwoochoi** [comment]
#58 finalized it. Closing now, thanks for initiating it!

**Pull request closed without merging**
